import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    species: "Musa AAB",
    variety: "Curaré Enano",
    biotization_type: "Biotizado +30%",
    senasa_cert: "SENASA-2024-001",
    stock_in_vitro: 5000,
    growth_speed: "Rápido",
    base_price: 3.53,
    region: "Loreto",
    line: "Musáceas",
    code: "PH-MUS-01",
    height: "2.1-2.9 m",
    tolerance: "Tolerante",
    technical_details: "Taxonomía: Eumusa AAB Plátano. Hábito de hoja: Encorvada. Aspecto del seudo tallo: Robusto. Ciclo: 294 días. Producción: 15-20 kg/racimo. Fruto: Curvado hacia arriba (45°), 21-31 cm.",
    image_url: "https://images.unsplash.com/photo-1628151015967-3386638f804e?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 2,
    species: "Musa AAA cv. Figue Rose Naine",
    variety: "Red Banano Enano",
    biotization_type: "Biotizado",
    senasa_cert: "SENASA-2024-005",
    stock_in_vitro: 3000,
    growth_speed: "Moderado",
    base_price: 3.80,
    region: "Loreto",
    line: "Musáceas",
    code: "PH-MUS-02",
    height: "3-4 m",
    tolerance: "Libre de Virus",
    technical_details: "Taxonomía: Musa AAA cv. Figue Rose Naine. Clon popular conocido como Plátano Rojo Enano Cubano. Planta robusta y resistente, sensible al frío (< 8°C). Reproducción in vitro garantizada.",
    image_url: "https://images.unsplash.com/photo-1594631252845-29fc4586c566?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 3,
    species: "Musa paradisiaca L.",
    variety: "Isla Maleño",
    biotization_type: "Biotizado",
    senasa_cert: "SENASA-2024-006",
    stock_in_vitro: 4000,
    growth_speed: "Moderado",
    base_price: 3.60,
    region: "San Martín",
    line: "Musáceas",
    code: "PH-MUS-03",
    height: "2.79 m",
    tolerance: "Vigilado",
    technical_details: "Taxonomía: Musa paradisiaca L. Producción: 95 bananos/planta (~20 Tn/ha). Seudo tallo: Verde rosado, 70 cm diámetro. Plantas precoces diseñadas para acortar fases fenológicas.",
    image_url: "https://images.unsplash.com/photo-1610832958506-aa56338406cd?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 4,
    species: "Aniba rosaeodora",
    variety: "Palo Rosa",
    biotization_type: "Biotizado Clonal",
    senasa_cert: "SENASA-2024-002",
    stock_in_vitro: 2000,
    growth_speed: "Moderado",
    base_price: 6.10,
    region: "San Martín",
    line: "Forestal",
    code: "PH-FOR-01",
    height: "18-35 m",
    tolerance: "Disponible",
    technical_details: "Taxonomía: Aniba rosaeodora Ducke. Árbol de porte mediano a grande. Corteza: Marrón claro (externa), Rosado claro y fragante (interna). Frutos: Drupas verdes globosas de 3.5 cm.",
    image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 5,
    species: "Cedrela odorata",
    variety: "Cedro",
    biotization_type: "Biotizado",
    senasa_cert: "SENASA-2024-003",
    stock_in_vitro: 1500,
    growth_speed: "Lento",
    base_price: 5.50,
    region: "Loreto",
    line: "Forestal",
    code: "PH-FOR-02",
    height: "40 m",
    tolerance: "Bajo Pedido",
    technical_details: "Taxonomía: Cedrela odorata L. Árbol de tronco recto. Copa: Grande, globosa y alargada. Corteza: Gruesa, áspera y acanalada de color café oscuro o gris. Fruto: Cápsula leñosa pentavalvar.",
    image_url: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 6,
    species: "Swietenia macrophylla",
    variety: "Caoba",
    biotization_type: "Biotizado",
    senasa_cert: "SENASA-2024-004",
    stock_in_vitro: 1200,
    growth_speed: "Lento",
    base_price: 6.50,
    region: "San Martín",
    line: "Forestal",
    code: "PH-FOR-03",
    height: "30-60 m",
    tolerance: "Disponible",
    technical_details: "Taxonomía: Swietenia macrophylla L. Árbol de gran tamaño. Copa: Diámetro de 14m con ramitas color castaño. Fuste: Recto, libre de ramas. Semillas: Sámaras aladas de 7.5 a 10 cm.",
    image_url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=800"
  }
];
